
# Phantom
/gate/world/daughters/name hof_brain
/gate/world/daughters/insert ImageRegularParametrisedVolume
/gate/hof_brain/geometry/setImage data/Realskull.h33
/gate/hof_brain/geometry/setRangeToMaterialFile data/attenuation_range.dat
/gate/hof_brain/placement/setTranslation 0. 0. 0. mm
/gate/hof_brain/placement/setRotationAxis 1 0 0
/gate/hof_brain/placement/setRotationAngle 0 deg
/gate/hof_brain/setSkipEqualMaterials 0
/gate/hof_brain/attachPhantomSD

